'use client';
import { ThemeToggle } from './theme-toggle';
import { PortfolioSections, Pathways } from './sections';
import { ArrowUpRight, ArrowDown, Code2 } from 'lucide-react';
export default function Home(){return <><Pathways/><header className="nav"><a className="brand" href="#home">PS<span>Priyanshi.</span></a><nav><a href="#highlight">ANI highlight</a><a href="#about">About</a><a href="#projects">Projects</a><a href="#journey">Journey</a><a href="#credentials">Credentials</a></nav><ThemeToggle/><a className="contact-link" href="#contact">Let’s talk <ArrowUpRight size={15}/></a></header><main id="home"><div className="eyebrow">001 // OVERVIEW <span/> GORAKHPUR, INDIA</div><section className="hero"><div><div className="availability"><i/> OPEN TO OPPORTUNITIES</div><h1>Develop.<br/>Discover.<br/><span>Make it matter.</span></h1><p className="intro">I’m <strong>Priyanshi Srivastava</strong> — a software engineer and BCA student turning curiosity into thoughtful digital experiences.</p><div className="actions"><a className="primary-link" href="#projects">Explore my work <ArrowUpRight size={18}/></a><a className="text-link" href="/Priyanshi-Srivastava-CV.pdf" download>Download CV <ArrowDown size={16}/></a></div><div className="hero-foot"><span>BCA ’27 · ITM, GIDA</span><a href="https://github.com/priyanshi02-lyt" target="_blank" rel="noreferrer"><Code2 size={16}/> GitHub ↗</a><a href="https://www.linkedin.com/in/priyanshi-srivastava-bb6a36421/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><figure className="hero-photo"><img src="/images/priyanshi-portrait.jpeg" alt="Priyanshi Srivastava in a grey blazer"/><figcaption><span>PRIYANSHI SRIVASTAVA<small>Software Engineer · AI & Data Enthusiast</small></span><span>↗</span></figcaption></figure></section><div className="stats"><div><strong>50+</strong><span>Projects & websites built</span></div><div><strong>04</strong><span>Industry experiences</span></div><div><strong>8.36</strong><span>BCA CGPA</span></div><a href="#about">A little more about me <ArrowDown size={20}/></a></div><PortfolioSections/></main></>}




